"""
Service layer for Code Agent API.

This module wraps the Code Agent CLI functionality to be used by FastAPI.
"""

import logging
import os

from src.code_agent.agent import CodeAgent
from src.utils.github_client import GitHubClient

logger = logging.getLogger(__name__)


class CodeAgentService:
    """Service for executing Code Agent tasks."""

    def __init__(self):
        """Initialize the Code Agent service."""
        self.github_token = os.getenv("GITHUB_TOKEN")
        self.openrouter_api_key = os.getenv("OPENROUTER_API_KEY")
        print(self.openrouter_api_key)
        self.model = os.getenv("CODE_AGENT_MODEL", "llama-3.3-70b-versatile")
        self.repos_dir = os.getenv("REPOS_DIR", "./repos")

        if not self.github_token:
            raise ValueError("GITHUB_TOKEN environment variable is required")
        if not self.openrouter_api_key:
            raise ValueError("OPENROUTER_API_KEY environment variable is required")

    def handle_issue(self, repo_full_name: str, issue_number: int) -> None:
        """
        Handle a new issue by running Code Agent.

        This method is executed in the background by FastAPI.

        Args:
            repo_full_name: Full repository name (owner/repo)
            issue_number: Issue number
        """
        logger.info(f"Starting Code Agent for issue #{issue_number} in {repo_full_name}")

        try:
            github_client, agent = self._initialize_agent()
            result = self._run_agent_for_issue(repo_full_name, issue_number, agent)

            if not result.success:
                logger.error(f"Agent failed: {result.error}")
                return

            self._create_and_push_pr(repo_full_name, issue_number, github_client, agent, result)
            agent.cleanup(verbose=True)

        except Exception as e:
            logger.error(f"Error handling issue #{issue_number}: {str(e)}", exc_info=True)

    def handle_pr_review(
        self, repo_full_name: str, issue_number: int, pr_number: int
    ) -> None:
        """
        Handle PR review feedback by running Code Agent.

        This method is executed in the background by FastAPI.

        Args:
            repo_full_name: Full repository name (owner/repo)
            issue_number: Issue number
            pr_number: Pull request number
        """
        logger.info(
            f"Starting Code Agent for PR #{pr_number} (issue #{issue_number}) in {repo_full_name}"
        )

        try:
            github_client, agent = self._initialize_agent()
            result = self._run_agent_for_pr(repo_full_name, issue_number, pr_number, agent)

            if not result.success:
                logger.error(f"Agent failed: {result.error}")
                return

            if not result.repo_path or "No changes needed" in result.output:
                logger.info(f"No changes needed for PR #{pr_number} - feedback is positive")
                return

            self._commit_pr_changes(pr_number, agent, result)
            agent.cleanup(verbose=True)

        except Exception as e:
            logger.error(f"Error handling PR #{pr_number}: {str(e)}", exc_info=True)

    def _initialize_agent(self) -> tuple[GitHubClient, CodeAgent]:
        """Initialize GitHub client and Code Agent."""
        github_client = GitHubClient(
            token=self.github_token,
            repos_dir=self.repos_dir,
        )

        agent = CodeAgent(
            github_client=github_client,
            model=self.model,
            api_key=self.openrouter_api_key,
        )

        return github_client, agent

    def _run_agent_for_issue(self, repo_full_name: str, issue_number: int, agent: CodeAgent):
        """Run agent to solve an issue."""
        logger.info(f"Analyzing issue #{issue_number}...")
        return agent.analyze_and_solve_issue(
            repo_name=repo_full_name,
            issue_number=issue_number,
            verbose=True,
        )

    def _run_agent_for_pr(
        self, repo_full_name: str, issue_number: int, pr_number: int, agent: CodeAgent
    ):
        """Run agent to address PR feedback."""
        logger.info(f"Analyzing PR #{pr_number} feedback...")
        return agent.analyze_and_solve_issue(
            repo_name=repo_full_name,
            issue_number=issue_number,
            pr_number=pr_number,
            verbose=True,
        )

    def _create_and_push_pr(
        self,
        repo_full_name: str,
        issue_number: int,
        github_client: GitHubClient,
        agent: CodeAgent,
        result,
    ) -> None:
        """Commit changes, push, and create Pull Request."""
        logger.info("Agent completed successfully, committing changes...")

        commit_message = f"Fix #{issue_number}: {github_client.get_issue(repo_full_name, issue_number).title}\n\nGenerated by Code Agent"
        agent.commit_and_push(result, commit_message, verbose=True)

        logger.info("Creating Pull Request...")
        pr_url = agent.create_pull_request(
            repo_name=repo_full_name,
            issue_number=issue_number,
            result=result,
            verbose=True,
        )

        logger.info(f"Successfully created PR: {pr_url}")

    def _commit_pr_changes(self, pr_number: int, agent: CodeAgent, result) -> None:
        """Commit and push changes for PR update."""
        logger.info("Agent completed successfully, checking for changes to commit...")

        commit_message = f"Address PR #{pr_number} feedback\n\nGenerated by Code Agent"
        try:
            agent.commit_and_push(result, commit_message, verbose=True)
            logger.info(f"Successfully updated PR #{pr_number}")
        except RuntimeError as e:
            if "No changes to commit" in str(e):
                logger.info(f"No changes needed for PR #{pr_number} - already in good state")
            else:
                raise
